### ISSUE TITLE
Build instructions/

### ISSUE THREAD

**Issue by afk11** [owenobyrne/aib-internet-banking-api#1]
Hi, great work on the software. I have a somewhat manual task I'm looking to automate, but don't come from a Java background. Could you document the build process? I've tried working through eclipse / IDEA, but no luck yet!

**Comment by afk11** [comment]
Actually, got it working just now! Thanks all the same :)

**Comment by owenobyrne** [comment]
Great stuff, I haven't been keeping it up to date recently, so let me know if you need any help. Some of the pages on AIB Online Banking may have changed.
