### ISSUE TITLE
Required PAC digits not returned in call to /v2/login/registration

### ISSUE THREAD

**Issue by joeltoby** [owenobyrne/aib-internet-banking-api#3]
`$ curl --data "REGISTRATION_NUMBER=12345678" $API_BASE/v2/login/registration`

Response:

`{"digit1":null,"digit2":null,"digit3":null,"sessionId":"2ddefca0-1d01-zzzz-yyyy-xxxxxxxxxxxx"}`

**Comment by owenobyrne** [comment]
Fixed by Pull request #2
